### ISSUE TITLE
Attributeerror: module cv2 has no attribute KNearest

### ISSUE THREAD

**Issue by Aftab890** [pavitrakumar78/Python-Custom-Digit-Recognition#1]
I am getting this KNearest error. **_Attributeerror: module cv2 has no attribute KNearest_** . The setup environment is following. 
Python3.5
tesnorflow1.10
opencv3.3
windows10

Kindly help me to resolve this error

**Comment by pavitrakumar78** [comment]
https://stackoverflow.com/questions/28297933/can-not-find-knearest-in-python-cv2

Use `cv2.ml.KNearest_create()` instead of `cv2.KNearest()`.  Please note that results may vary if you are using different versions of libraries. You may need to make more changes to the code to make it compatible with recent libraries.

**Comment by pavitrakumar78** [comment]
@Aftab890 I have updated the readme and the code (`NEW_digi_recog.py`). You may want to take a look at the newer code and the comments inside the code.
